apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  namespace: test
  name: frontend
spec:
  image: nginx:1.23.3
  port: 80
  labels:
    app.kubernetes.io/instance: test
  ingresses:
    - test.com
  accessPolicy:
    outbound:
      rules:
        - application: backend